// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class MetodosPagoConfiguration : IEntityTypeConfiguration<MetodosPago>
    {
        public void Configure(EntityTypeBuilder<MetodosPago> entity)
        {
            entity.HasKey(e => e.IdMetodoPago);

            entity.Property(e => e.FechaAlta).HasColumnType("date");

            entity.Property(e => e.FechaBaja).HasColumnType("date");

            entity.Property(e => e.MetodoPago)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MetodosPago> entity);
    }
}
